### ISSUE TITLE
All references to javascript files and styling has broken

### ISSUE THREAD

**Issue by NedgoIO** [BlackrockDigital/startbootstrap-freelancer-jekyll#6]
All references to javascript files and styling has broken. Check out the demo, I can't find the correct versions of the files to fix my site... Please assist.

**Comment by thedanheller** [comment]
I'm having the same issue. Even the [demo](http://blackrockdigital.github.io/startbootstrap-freelancer-jekyll/) page is broken.

**Comment by NedgoIO** [comment]
Yeah, I just need the file versions that were used and I can fix it. Does anyone know?

**Comment by thedanheller** [comment]
```
jquery-1.12.4.min.js
bootstrap/3.3.6/js/bootstrap.min.js
jquery-easing/1.3/jquery.easing.min.js

/js/classie.js
/js/cbpAnimatedHeader.min.js

3.3.6/css/bootstrap.min.css
/css/freelancer.css
4.6.3/css/font-awesome.min.css
```

**Comment by NedgoIO** [comment]
Your the freaking man, I don't care what anyone else says. ;)

**Comment by davidtmiller** [comment]
The base template was updated so you can replace the file paths in the template with the new CDN links in the meantime using these file paths:

JavaScript

`<!-- jQuery -->`
`<script src="http://sbootstrap-freelancer.startbootstrapc.netdna-cdn.com/vendor/jquery/jquery.min.js"></script>`
`<!-- Bootstrap Core JavaScript -->`
`<script src="http://sbootstrap-freelancer.startbootstrapc.netdna-cdn.com/vendor/bootstrap/js/bootstrap.min.js"></script>`
`<!-- Plugin JavaScript -->`
`<script src="http://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"></script>`
`<!-- Contact Form JavaScript -->`
`<script src="http://sbootstrap-freelancer.startbootstrapc.netdna-cdn.com/js/jqBootstrapValidation.js"></script>`
`<script src="http://sbootstrap-freelancer.startbootstrapc.netdna-cdn.com/js/contact_me.js"></script>`
`<!-- Custom Theme JavaScript -->`
`<script src="http://sbootstrap-freelancer.startbootstrapc.netdna-cdn.com/js/freelancer.min.js"></script>`

CSS

`<!-- Bootstrap Core CSS -->`
`<link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">`

`<!-- Theme CSS -->`
`<link href="css/freelancer.min.css" rel="stylesheet">`

`<!-- Custom Fonts -->`
`<link href="vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
<link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">`
`<link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css">`

You'll also need to add the `.navbar-custom` class to the navigation as well as the `mainNav` ID since two of the jQuery plugins were dropped in favor of something else.

I am still figuring out a good way to sync the Jekyll version of the theme with the base HTML/CSS version - I'm doing it now through a CDN but if anyone has any better ideas I am open to hearing them!

Thanks for pointing out this issue, hopefully this solves everything!

**Comment by daniloprates** [comment]
thanks @davidtmiller! where do I find the `.css` files?

**Comment by davidtmiller** [comment]
It's in the post above right below the JS stuff. You also need to add the custom class and ID to the navbar.

**Comment by daniloprates** [comment]
sorry, I mean the proper files to download and add them to the project

**Comment by davidtmiller** [comment]
You can get all of the files on the Freelancer base theme's repo here: https://github.com/BlackrockDigital/startbootstrap-freelancer

**Comment by davidtmiller** [comment]
Closing this for now since it's fixed.

**Comment by thedanheller** [comment]
that's great, thanks!
